def COLOR_MAP = [
    'SUCCESS': 'good',  // good in slack means green color
    'FAILURE': 'danger', // danger=red color
]
pipeline {
    agent any
    
    environment {
        cluster = "ProductionCluster"
        service = "productionservice"
    }
    stages {    
        stage('Deploy to Production ECS '){
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }

            }
        }

    }
    post {
        always {                            //always this will be executed 
            echo 'Slack Notifications.'    //print message
            slackSend channel: '#jenkins',   //slackSend is the plugin we install  + channel name
                color: COLOR_MAP[currentBuild.currentResult],   // jenkins globar variables
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }        
} 